### PR TITLE
Fix inconsistent trees from getindex and merge.

### LINKED ISSUE #39: Missing root when accessing by regex
It seems like `File`s no longer have their absolute path intact after accessing them with a regex:

```julia
julia> ft = maketree("a" => ["b" => ["c" => ["d"]]]);

julia> ft |> files |> first # Expected answer
File(a\b\c\d)

julia> ft[r".*/c/d"] |> files |> first # Root is dropped :(
File(b\c\d)

julia> ft[glob"*/c/d"] |> files |> first # No problem!
File(a\b\c\d)

julia> ft["b/c/d"] # No problem!
File(a\b\c\d)
```

### PR DESCRIPTION
**Pull request by DrChainsaw**
Fixes #39 

Testing revealed that the root issue is that `getindex` for both globs and regexps returns a tree where the children of the root does not have the root as parent. Same thing also happens after `merge`.

Not sure if this is intentional, but it seems to me that a tree like this is inconsistent and should be considered invalid. Another option could be to add a call to `setparent` in the convenience “copy” constructor for `FileTree` if one wants to be really strict about not allowing such trees.

It turned out that `mv` and `cp` (or in fact ` regex_rewrite_tree` and `attach`) relied on this behavior to leave the root out of all processing. I first tried to change `attach` to not add the root node (i.e last line changed to `merge(t, t1; combine=combine)` and assume that `path` argument included the path to the root. 

This did however cause problems when root node is a subdirectory as it would change the tree to use the root of the root node as, uhm, root (i.e if root node has path a/b then the returned tree would have `a` as root and `b` as its child). This also had the adverse consequence that the public API for `mv` and `cp` would break as regexes where now matched against the whole path including the root node. Both these problems where caught by the `mv` tests in taxi.jl. 

Instead I resorted to just truncating the canonical path from behind in `regex_rewrite_tree`. Not sure if this is the most elegant way to do it.

### CODE REVIEW

**Comment by DrChainsaw** [comment]
@shashi Bump?

In case you have more pressing matters on your table or just don't want to context switch: I can work around the issue from the outside by just adding ` |> setparent` after any getindex/mv/merge so this is just a bit of an inconvenience for me atm.

File: src/patterns.jl [hunk 1]
```diff
@@ -73,7 +73,7 @@ function _regex_map(yes, no, t::FileTree, regex::Regex, toplevel=true)
     if isempty(cs)
         return no(t)
     else
-        return FileTree(t; children=cs)
+        return FileTree(t; children=cs) |> setparent
```
Comment (shashi) [inline src/patterns.jl:76]: Setparent here may copy sub trees more times than necessary. I’d suggest moving this to the place which calls _regex_map or _glob_map

**Comment by shashi** [comment]
Sorry about the delay here. This got drowned out in the other notifications. Thanks for pinging again! This looks good to me, except for that comment I left.

File: src/patterns.jl (hunk 1 above)
Comment (DrChainsaw) [reply src/patterns.jl:76]: I guess you mean the getindex functions? Sure thing! Will commit once tests finish.

**Comment by DrChainsaw** [comment]
Thanks for checking!

Do you have an opinion on this:

> Another option could be to add a call to setparent in the convenience “copy” constructor for FileTree if one wants to be really strict about not allowing such trees.

Is there some reason one should be able to create trees where nodes are not the parent of their children?
